AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      Timeout: 3
      CodeUri: build
      Environment:
        Variables:
          URL: http://www.amazon.com
